# Generated by Django 4.1.5 on 2023-01-26 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0003_skill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('view_history', 'Can view history')]},
        ),
    ]
